from __future__ import annotations

from dataclasses import dataclass
from typing import Dict

from .indicator_metrics import SimulationSummary
from .time_series import TimeframeMetricSeries, TimeframeSeries


__all__ = ["CollectionResult"]


@dataclass
class CollectionResult:
    """Container for the results produced by ``collect_metrics``.

    Attributes:
        payload: JSON-compatible payload containing the collected metrics.
        summary: Simulation summary generated by the indicator simulator.
        main_series: Primary timeframe series used for analysis.
        multi_timeframe_series: Additional timeframe series keyed by timeframe string.
        multi_timeframe_strength: Trend strength series per timeframe and symbol.
        multi_symbol_series: Series for correlated symbols used in multi-symbol analysis.
    """

    payload: Dict[str, object]
    summary: SimulationSummary
    main_series: TimeframeSeries
    multi_timeframe_series: Dict[str, TimeframeSeries]
    multi_timeframe_strength: Dict[str, TimeframeMetricSeries]
    multi_symbol_series: Dict[str, TimeframeSeries]
